"""Convert the standalone index.html into an Artifact-safe fragment.

The Artifact publisher wraps the file it is given in its own
<!doctype html><head>...</head><body>FILE</body> skeleton, so handing it a
complete document nests document-level tags inside a body.

index.html has no explicit <head>/<body> — it relies on implicit parsing —
so the conversion is mostly stripping the doctype and the <html> wrapper.
The explicit-tag case is handled too, so this keeps working if the source
ever grows real <head>/<body> tags.

Output is a single self-contained fragment; no external requests are added
or removed, and the script reports any that exist so a CSP failure cannot
arrive as a surprise.

    py -3 build_artifact.py            -> writes artifact_tape.html
"""
import io, re, sys

SRC = 'index.html'
OUT = 'artifact_tape.html'

s = io.open(SRC, encoding='utf-8').read()

head = re.search(r'<head[^>]*>(.*?)</head>', s, re.S)
body = re.search(r'<body[^>]*>(.*?)</body>', s, re.S)

if head and body:
    inner = head.group(1).strip() + '\n' + body.group(1).strip()
else:
    # implicit document: drop the doctype and the <html>/</html> wrapper
    inner = re.sub(r'^\s*<!doctype[^>]*>', '', s, flags=re.I)
    inner = re.sub(r'<html[^>]*>', '', inner, count=1, flags=re.I)
    inner = re.sub(r'</html\s*>\s*$', '', inner, flags=re.I)
    inner = inner.strip()

# charset is set by the wrapper's own head; a second one inside body is inert
# noise. Everything else (title, meta, style, script, JSON-LD) is kept.
inner = re.sub(r'<meta\b[^>]*charset[^>]*>\s*', '', inner, flags=re.I)

out = ('<!-- Generated by build_artifact.py from index.html — do not edit by hand. -->\n'
       + inner)

io.open(OUT, 'w', encoding='utf-8', newline='').write(out)

external = re.findall(r'(?:src|href)\s*=\s*"(https?://[^"]+)"', out)
leftovers = re.findall(r'</?(?:html|head|body)\b[^>]*>', out, flags=re.I)

print('wrote %s  (%.0f KB)' % (OUT, len(out.encode('utf-8')) / 1024))
print('document-level tags left in the fragment: %d %s'
      % (len(leftovers), leftovers[:4] if leftovers else ''))
print('title preserved: %s' % bool(re.search(r'<title>', out, re.I)))
print('external references: %d' % len(external))
for u in sorted(set(external)):
    print('   ', u)
sys.exit(1 if leftovers else 0)
